### PR TITLE
LOD level_changed fix

### LINKED ISSUE #11: LOD level_changed VRML conflict
https://x3d-lodlevel-test.glitch.me/x_ite.html

tests the LOD level_changed event by routing its value to a Switch node. Text should be displayed when the LOD level changes but it is not.

https://glitch.com/edit/#!/x3d-lodlevel-test?path=LODwithDifferentShapes.x3d

works in other X3D browsers.

I only checked if the level_changed field is actually implemented in x_ite, and it is. Not sure where to go from there.

### PR DESCRIPTION
**Pull request by andreasplesch**
fixes #11 
guard aliasing of children to level to prevent shadowing of level_changed for X3D encoding

tests here (X3D):
https://x-ite-lodlevel-fix.glitch.me/x_ite.html

and here (VRML):
https://x-ite-lodlevel-fix.glitch.me/x_ite_vrml.html

### CODE REVIEW

**Comment by create3000** [comment]
Thank you for finding this bug. But this also means that all VRML aliases must be guarded.

**Comment by andreasplesch** [comment]
LOD may be the only node where a VRML field name ('level') was renamed (to 'children') but x3d encoding retained another, outputOnly field with the same name ('level_changed').

To be safe, it would not hurt to guard all VRML aliases.

**Comment by andreasplesch** [comment]
Another approach is to put the guard into an .addVrmlFieldAlias method which would be used instead of the addAlias method for the few nodes which use it for the vrml field names.

On the other hand a discussion on x3d-public confirms that only LOD level needs that check.

**Comment by andreasplesch** [comment]
Thanks.

**Pull request closed without merging**
